set -x
echo "CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES"
export VLLM_ATTENTION_BACKEND=XFORMERS
export WANDB_MODE=offline
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
export HYDRA_FULL_ERROR=1

TRAIN_DATA=${TRAIN_DATA:-data/train.parquet}
VAL_DATA=${VAL_DATA:-data/dev.parquet}
TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE:-4}
VAL_BATCH_SIZE=${VAL_BATCH_SIZE:-24}
MAX_PROMPT_LENGTH=${MAX_PROMPT_LENGTH:-28000}
MAX_RESPONSE_LENGTH=${MAX_RESPONSE_LENGTH:-512}
ACTOR_LR=${ACTOR_LR:-1e-5}
PPO_MINI_BATCH_SIZE=${PPO_MINI_BATCH_SIZE:-8}
PPO_MICRO_BATCH_SIZE=${PPO_MICRO_BATCH_SIZE:-8}
LOG_PROB_MICRO_BATCH_SIZE=${LOG_PROB_MICRO_BATCH_SIZE:-8}
KL_LOSS_COEF=${KL_LOSS_COEF:-0.001}
KL_CTRL_COEF=${KL_CTRL_COEF:-0.001}
ROLLOUT_TP_SIZE=${ROLLOUT_TP_SIZE:-8}
ROLLOUT_GPU_MEMORY_UTILIZATION=${ROLLOUT_GPU_MEMORY_UTILIZATION:-0.8}
ROLLOUT_N_AGENT=${ROLLOUT_N_AGENT:-8}
ROLLOUT_TEMPERATURE=${ROLLOUT_TEMPERATURE:-1}
PROJECT_NAME=${PROJECT_NAME:-train}
EXPERIMENT_NAME=${EXPERIMENT_NAME:-train}
SAVE_FREQ=${SAVE_FREQ:-10}
TEST_FREQ=${TEST_FREQ:-10}
TOTAL_EPOCHS=${TOTAL_EPOCHS:-8}

python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files="$TRAIN_DATA" \
    data.val_files="$VAL_DATA" \
    data.train_batch_size="$TRAIN_BATCH_SIZE" \
    data.val_batch_size="$VAL_BATCH_SIZE" \
    data.max_prompt_length="$MAX_PROMPT_LENGTH"\
    data.max_response_length="$MAX_RESPONSE_LENGTH" \
    actor_rollout_ref.model.path=$BASE_MODEL \
    actor_rollout_ref.actor.optim.lr="$ACTOR_LR" \
    actor_rollout_ref.model.use_remove_padding=true \
    actor_rollout_ref.actor.ppo_mini_batch_size="$PPO_MINI_BATCH_SIZE" \
    actor_rollout_ref.actor.ppo_micro_batch_size="$PPO_MICRO_BATCH_SIZE" \
    actor_rollout_ref.actor.use_kl_loss=true \
    actor_rollout_ref.actor.kl_loss_coef="$KL_LOSS_COEF"\
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.model.enable_gradient_checkpointing=true \
    actor_rollout_ref.actor.fsdp_config.param_offload=true \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=true \
    actor_rollout_ref.actor.fsdp_config.offload_policy=true\
    actor_rollout_ref.rollout.log_prob_micro_batch_size="$LOG_PROB_MICRO_BATCH_SIZE" \
    actor_rollout_ref.rollout.tensor_model_parallel_size="$ROLLOUT_TP_SIZE" \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization="$ROLLOUT_GPU_MEMORY_UTILIZATION" \
    actor_rollout_ref.actor.state_masking=true \
    actor_rollout_ref.rollout.n=1 \
    actor_rollout_ref.rollout.n_agent="$ROLLOUT_N_AGENT" \
    actor_rollout_ref.rollout.temperature="$ROLLOUT_TEMPERATURE" \
    actor_rollout_ref.ref.log_prob_micro_batch_size="$LOG_PROB_MICRO_BATCH_SIZE" \
    actor_rollout_ref.ref.fsdp_config.param_offload=true \
    algorithm.kl_ctrl.kl_coef="$KL_CTRL_COEF" \
    trainer.critic_warmup=0 \
    trainer.logger=['console','wandb'] \
    trainer.balance_batch=true \
    trainer.val_before_train=false \
    +trainer.val_only=false\
    trainer.project_name="$PROJECT_NAME" \
    trainer.experiment_name="$EXPERIMENT_NAME" \
    trainer.n_gpus_per_node=$N_GPUS \
    trainer.nnodes=1 \
    trainer.save_freq="$SAVE_FREQ" \
    trainer.test_freq="$TEST_FREQ" \
    trainer.total_epochs="$TOTAL_EPOCHS" 2>&1 | tee "$LOG_FILE"
